# Generated by Django 4.2.7 on 2025-12-27 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_item_rooms_to_fk(apps, schema_editor):
    Item = apps.get_model('inventory', 'Item')
    Room = apps.get_model('inventory', 'Room')

    def ensure_room(name):
        if not name:
            name = 'General Storage'
        room = Room.objects.filter(room_name=name).first()
        if room:
            return room
        # Create unique room_key
        rk = f"AUTO-{uuid.uuid4().hex[:8]}"
        return Room.objects.create(room_name=name, room_type='storage', room_key=rk, location='Unknown')

    for item in Item.objects.all():
        # item.room is currently a text field
        current = item.room or 'General Storage'
        room = ensure_room(current)
        # Temporarily store the FK id as text; the upcoming AlterField will convert it to integer FK
        item.room = str(room.pk)
        item.save(update_fields=['room'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_roomkey_keyauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=50)),
                ('room_key', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['room_name'],
            },
        ),
        migrations.RunPython(migrate_item_rooms_to_fk, migrations.RunPython.noop),
        migrations.CreateModel(
            name='RoomItemHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('from_room', models.ForeignKey(db_column='from_room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from', to='inventory.room')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='room_history', to='inventory.item')),
                ('to_room', models.ForeignKey(db_column='to_room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='inventory.room')),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_item_history',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='roomkey',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='KeyAuditLog',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='RoomKey',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.room'),
        ),
    ]
