# Generated by Django 4.2.7 on 2025-12-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_room_roomitemhistory_remove_purchase_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.BooleanField(default=False),
        ),
    ]
