# Generated by Django 4.2.7 on 2025-12-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_room_description_remove_room_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
