# Generated by Django 4.2.7 on 2025-12-31 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_room_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('key_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('lost', 'Lost'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('last_location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room_keys',
                'ordering': ['room_name', 'key_number'],
            },
        ),
        migrations.CreateModel(
            name='KeyBorrow',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('borrowed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_return_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, db_column='approver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_key_borrows', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(db_column='borrower_id', on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_keys', to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(db_column='key_id', on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to='inventory.roomkey')),
            ],
            options={
                'db_table': 'key_borrows',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('lost', 'Lost'), ('found', 'Found'), ('maintenance', 'Sent to Maintenance'), ('restored', 'Restored'), ('created', 'Created'), ('borrowed', 'Borrowed'), ('returned_borrow', 'Returned from Borrow')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(db_column='key_id', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.roomkey')),
                ('performed_by', models.ForeignKey(db_column='performed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'key_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
