# Generated by Django 4.2.7 on 2026-02-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_pendingstocktransaction_pendingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='requisition',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
