# Generated by Django 4.2.7 on 2026-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_requisition_department_requisition_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='expected_return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='return_duration_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='requisition',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
